server:
  port: 30112

# spring 配置
spring:
  application:
    name: alinesno-infra-base-id-boot
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  devtools:
    restart:
      enabled: true